replicaCount: 1

image:
  repository: ghcr.io/nomadphone/message-router
  pullPolicy: IfNotPresent

mongo:
  connectionOptions: "&ssl=false"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: api.nomadphone.com.br
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: api.nomadphone.com.br-tls
     hosts:
       - api.nomadphone.com.br

resources:
  requests:
    cpu: 20m
    memory: 20Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80